name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Publish package
        run: mvn -B -X -e deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
